### **Boosting Algorithms**

In [52]:
%pip install xgboost

Requirement already satisfied: xgboost in c:\users\ruban\appdata\roaming\python\python313\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\ruban\appdata\roaming\python\python313\site-packages (from xgboost) (2.4.4)
Requirement already satisfied: scipy in c:\users\ruban\appdata\roaming\python\python313\site-packages (from xgboost) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

In [1]:
!pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lightgbm in c:\users\ruban\appdata\roaming\python\python313\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\ruban\appdata\roaming\python\python313\site-packages (from lightgbm) (2.4.4)
Requirement already satisfied: scipy in c:\users\ruban\appdata\roaming\python\python313\site-packages (from lightgbm) (1.17.1)

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("insurance_pre.csv")

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

### **Data collection & Pre-processing**

In [5]:
# Encoding: Convert the categorical columns (SEX/SMOKER) into numerical
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

# Since the BMI data already within a range as in standard, I not standardize again

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
# Separate the input and output variables
X = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
y = dataset["charges"]

In [9]:
X

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [10]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [11]:
# Split the training and test dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

### 1. Ada Boosting (Adaptive Boosting)

In [12]:
from sklearn.ensemble import AdaBoostRegressor

In [13]:
# https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostRegressor.html

regressor = AdaBoostRegressor(n_estimators=100, random_state=0)
regressor.fit(X_train, y_train)

AdaBoostRegressor(n_estimators=100, random_state=0)

In [14]:
y_pred = regressor.predict(X_test)

In [15]:
from sklearn.metrics import r2_score

score = r2_score(y_test, y_pred)
print("R2 Score for  AdaBoost: ", score)

R2 Score for  AdaBoost:  0.8447476929154872

### 2. XGBoost (Extreme Gradient Boosting)

In [16]:
import xgboost as xgb

In [17]:
regressor = xgb.XGBRegressor(max_depth=3, learning_rate=0.1, n_estimators=100)
regressor.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [18]:
y_pred = regressor.predict(X_test)

In [19]:
score = r2_score(y_test, y_pred)
print("XGBoost (Extreme Gradient Boosting): ", score)

XGBoost (Extreme Gradient Boosting):  0.8883086953350264

### 3. LG Boost (Light Gradient Boosting)

In [20]:
# https://www.geeksforgeeks.org/machine-learning/regression-using-lightgbm/

from lightgbm import LGBMRegressor

In [ ]:
regressor = LGBMRegressor(metric='rmse')
regressor.fit(X_train, y_train)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
score = r2_score(y_test, y_pred)
print("LG Boost (Light Gradient Boosting): ", score)