### Grid Search using SVM
Inputs and outputs not splited. Directly passing to the model

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("/content/insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

### **Pre-Processing**

In [5]:
# The columns sex and smoker has the categorical data needs to do the one-hot-endocing.
# This step will convert the values to numerical

In [6]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [7]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

### **Separate the input and output variables**

In [9]:
X = dataset[["age", "bmi", "children", "sex_male", "smoker_yes"]]
y = dataset["charges"]

In [10]:
X

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [11]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from sklearn.metrics import r2_score

grid_param = {
                "kernel": ["linear", "poly", "rbf", "sigmoid"],
                "C": [10, 100, 1000, 2000, 3000],
                "gamma": ["auto", "scale"]
             }

grid = GridSearchCV(SVR(), grid_param, refit = True, verbose = 3, n_jobs = 1)
grid.fit(X, y)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
[CV 1/5] END ..C=10, gamma=auto, kernel=linear;, score=-0.019 total time=   0.1s
[CV 2/5] END ...C=10, gamma=auto, kernel=linear;, score=0.030 total time=   0.1s
[CV 3/5] END ...C=10, gamma=auto, kernel=linear;, score=0.022 total time=   0.1s
[CV 4/5] END ...C=10, gamma=auto, kernel=linear;, score=0.003 total time=   0.1s
[CV 5/5] END ..C=10, gamma=auto, kernel=linear;, score=-0.067 total time=   0.1s

In [ ]:
# Print best parameter after tuning
re = grid.cv_results_

print("The best parameters {}:".format(grid.best_params_))

The best parameters {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [ ]:
table = pd.DataFrame().from_dict(re)
# print(table)

In [ ]:
age = float(input("Age: "))
bmi = float(input("BMI: "))
children = float(input("Children: "))
gender = float(input("Gender Male=0, Female=1: "))
smoker = float(input("Smoker Yes=0, No=1: "))

predicted_charges = grid.predict([[age, bmi, children, gender, smoker]])

smoker = "smoking" if smoker == 0 else "non-smoking"
print("Using SVM: {} years old {} {} having {} BMI and {} kids, the charges will be", age, smoker, gender, bmi, children, predicted_charges)

Age: 42
BMI: 22.2
Children: 2
Gender Male=0, Female=1: 0
Smoker Yes=0, No=1: 0
Using SVM: [14407042.02227001]