In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("/content/insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

### **Pre-Processing**

In [5]:
# The columns sex and smoker has the categorical data needs to do the one-hot-endocing.
# This step will convert the values to numerical

In [6]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [7]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

### **Separate the input and output variables**

In [12]:
X = dataset[["age", "bmi", "children", "sex_male", "smoker_yes"]]
y = dataset["charges"]

In [13]:
X

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [14]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

### **Split the training and test dataset**

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

### **1. Multiple Linear Regression**

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Multiple Linear Regression:", score)

Multiple Linear Regression: 0.7894790349867009

### **2. SVM**

In [18]:
from sklearn.svm import SVR
regressor = SVR(kernel="linear")
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("SVM:", score)

SVM: -0.11166128719608448

### **3. DecisionTree**

In [19]:
from sklearn.tree import DecisionTreeRegressor

# criterion {squared_error, friedman_mse, absolute_error, poisson}
# splitter {best, random}

regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='best')
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Decision Tree (absolute_error, best):", score)

Decision Tree (absolute_error, best): 0.6610346986590394

In [20]:
regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='random')
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Decision Tree (absolute_error, random):", score)

Decision Tree (absolute_error, random): 0.6996093484280177

In [23]:
regressor = DecisionTreeRegressor(criterion='friedman_mse', splitter='best')
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Decision Tree (friedman_mse, best):", score)

Decision Tree (friedman_mse, best): 0.685759408761859

In [24]:
regressor = DecisionTreeRegressor(criterion='friedman_mse', splitter='random')
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Decision Tree (friedman_mse, random):", score)

Decision Tree (friedman_mse, random): 0.7286996143006814

In [25]:
regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='best')
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Decision Tree (absolute_error, best):", score)

Decision Tree (absolute_error, best): 0.6707504283929027

In [26]:
regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='random')
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Decision Tree (absolute_error, random):", score)

Decision Tree (absolute_error, random): 0.6899738668987889

In [28]:
regressor = DecisionTreeRegressor(criterion='poisson', splitter='best')
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Decision Tree (poisson, best):", score)

Decision Tree (poisson, best): 0.7110141173877638

In [29]:
regressor = DecisionTreeRegressor(criterion='poisson', splitter='random')
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("Decision Tree (poisson, random):", score)

Decision Tree (poisson, random): 0.6979627645329558

### **4. RandomForest**

In [31]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("RandomForest (n_estimators=10):", score)

RandomForest (n_estimators=10): 0.83303041340085

In [32]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=25, random_state=0)
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("RandomForest (n_estimators=25):", score)

RandomForest (n_estimators=25): 0.8507659578312787

In [33]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=50, random_state=0)
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("RandomForest (n_estimators=50):", score)

RandomForest (n_estimators=50): 0.8498329315421834

In [34]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=75, random_state=0)
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("RandomForest (n_estimators=75):", score)

RandomForest (n_estimators=75): 0.852461077725205

In [35]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=100, random_state=0)
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("RandomForest (n_estimators=100):", score)

RandomForest (n_estimators=100): 0.8538307913484513

In [36]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=200, random_state=0)
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

score = r2_score(y_test, y_pred)
print("RandomForest (n_estimators=200):", score)

RandomForest (n_estimators=200): 0.8524777475124578

### **Deployment**

In [37]:
import pickle
filename = "finalized_model_Insurance.sav"

In [38]:
pickle.dump(regressor, open(filename, "wb"))

In [39]:
loaded_model = pickle.load(open(filename, "rb"))

In [40]:
result = loaded_model.predict([[42, 22.4, 2, 0, 0]])
print("Predicted cost for 42 yrs, 22.4 BMI, number of kids = 2, Male and Non Smoker is", result)

Predicted cost for 42 yrs, 22.4 BMI, number of kids = 2, Male and Non Smoker is [8439.72816425]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(